local treesitter = require("nvim-treesitter.configs")
treesitter.setup({
	ensure_installed = {
		"bash",
		"go",
		"php",
		"phpdoc",
		"java",
		"python",
		"lua",
		"javascript",
		"typescript",
		"tsx",
		"html",
		"css",
		"scss",
		"vue",
		"json",
		"yaml",
		"markdown",
		"markdown_inline",
		"make",
	},
	highlight = { enable = true },
	autopairs = { enable = true },
	context_commentstring = { enable = true, enable_autocmd = false },
	indent = { enable = true },
	autotag = { enable = true },
})
